import {
  Activity,
  Award,
  BookOpen,
  CalendarCheck,
  ClipboardCheck,
  Database,
  DollarSign,
  FilePen,
  GraduationCap,
  HardDrive,
  LifeBuoy,
  MessageSquare,
  Radio,
  Server,
  TrendingUp,
  UserCheck,
  UserPlus,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "../api/types";

/** Maps the API's icon identifiers to concrete Lucide components. */
export const iconRegistry: Record<IconKey, LucideIcon> = {
  users: Users,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "file-pen": FilePen,
  "clipboard-check": ClipboardCheck,
  radio: Radio,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  award: Award,
  "trending-up": TrendingUp,
  "dollar-sign": DollarSign,
  "hard-drive": HardDrive,
  activity: Activity,
  database: Database,
  server: Server,
  "message-square": MessageSquare,
  "life-buoy": LifeBuoy,
  "calendar-check": CalendarCheck,
};
